const clients = [
    { id: 1, name: "SHREE PILANI", location: "JAIPUR" },
    { id: 2, name: "RSWM DENIM LNJ", location: "Banswara" },
    { id: 3, name: "RSWM SOLER PLANT Ltd.", location: "Banswara" },
    { id: 4, name: "RSWM POWER PLANT MORDI", location: "Banswara" },
    { id: 5, name: "Somani Export Pvt. Ltd.", location: "Jaipur" },
    { id: 6, name: "Cheer Sagar Export", location: "Jaipur" },
    { id: 7, name: "Goyal Arts", location: "Jaipur" },
    { id: 8, name: "Shree Ram Overseas Pvt. Ltd.", location: "Jaipur" },
    { id: 9, name: "Lodha Impex", location: "Jaipur" },
    { id: 10, name: "INDUS CARTEX", location: "Jaipur" },
    { id: 11, name: "MARC FASHION", location: "Jaipur" },
    { id: 12, name: "GORIWALA EXPORT", location: "Jaipur" },
    { id: 13, name: "Metro Cash & Carry", location: "Jaipur, Panjab" },
    { id: 14, name: "Bansal education classes", location: "Gopalpura" },
    { id: 15, name: "Times Coaching Classes", location: "Jaipur" },
    { id: 16, name: "LODHA (LNJ) RSWM", location: "Banswara" },
    { id: 17, name: "Regional collage", location: "Sitapura" },
    { id: 18, name: "Pratham education foundation", location: "Jaipur" },
    { id: 19, name: "CENTER SCHOOL", location: "Banswara" },
    { id: 20, name: "Pearl Suryavanshi Apartment", location: "Jaipur" },
    { id: 21, name: "Deep Sikha Collage", location: "Jaipur" },
    { id: 22, name: "Apex collage sitapura", location: "Sitapura" },
    { id: 23, name: "Mjrp University", location: "Sitapura" },
    { id: 24, name: "Pinkcity Expressway(NH 8)", location: "Manesar" },
    { id: 25, name: "Dabariya Polly wood", location: "Jaipur" },
    { id: 26, name: "Venus Gems Art", location: "Jaipur" },
    { id: 27, name: "Agarwal Advertising Company", location: "Jaipur" },
    { id: 28, name: "Hotel Deveraj Niwas", location: "Jaipur" },
    { id: 29, name: "Guru Pragya Real Estate", location: "Jaipur" },
    { id: 30, name: "Shiv Gyan Luxara", location: "Jaipur" },
    { id: 31, name: "Kirti Builder and Developer", location: "Jaipur" },
    { id: 32, name: "Namdev Builder and Developer", location: "Jaipur" },
    { id: 33, name: "USHA Engineering Product Pvt. Ltd.", location: "Jaipur" },
    { id: 34, name: "Hariom Builder and Developer", location: "Jaipur" },
    { id: 35, name: "Danik Navjyoti", location: "Jaipur" },
    { id: 36, name: "Anil Steel", location: "Jaipur" },
    { id: 37, name: "Kendriyavihar II Jagatpura (AOWA)", location: "Jagatpura, Jaipur" },
    { id: 38, name: "ISCO Tracks Sleeper Plant", location: "Faridabad & Khattu" },
    { id: 39, name: "Vitromade Health Care", location: "Jaipur" },
    { id: 40, name: "CSIR (Central Electronics Engineering Research Institute)", location: "Pilani" },
    { id: 41, name: "Council of Scientific & Industrial Research", location: "Jaipur" },
    { id: 42, name: "Hindustan salt ltd", location: "Sambhar" },
    { id: 43, name: "Balaji Exports", location: "Jaipur" },
    { id: 44, name: "K E C International Ltd.", location: "Jaipur" },
    { id: 45, name: "S IEMET Goner", location: "Jaipur" },
    { id: 46, name: "Kendriya Vidayalaya Sagathan", location: "Jaipur" },
    { id: 47, name: "Regional Training Institute, Indian Audit & Accounts Department", location: "Jaipur" },
    { id: 48, name: "Regional Training Institute, RTI (AG COLONY)", location: "Jaipur" },
    { id: 49, name: "Rajasthan Rajya Vidyut Utpadan Nigam", location: "Banswara" },
    { id: 50, name: "Bhiwadi Indrigrated Vikas Pradhikaran (BIDA)", location: "Bhiwadi" },
    { id: 51, name: "Jawahar Navodaya Vidhayalay Nasirabad", location: "Ajmer" },
    { id: 52, name: "RUHS Dental Collage", location: "Jaipur" },
    { id: 53, name: "Karshi Upaj Mandi", location: "Chomu" },
    { id: 54, name: "CGST", location: "Sikar" },
    { id: 55, name: "Gram Panchayat Laxman Ghra", location: "Sikar" },
    { id: 56, name: "Vivakanand Kendary Vidhyalya", location: "Bhilwara" },
    { id: 57, name: "IBIS Jaipur Intergloble Hotel Pvt. Ltd.", location: "Jaipur" },
    { id: 58, name: "LE MERIDIEN Jaipur (A Unit of Mayank)", location: "Jaipur" },
    { id: 59, name: "Rangwanis Hotels Pvt. Ltd.", location: "Ajmer" },
    { id: 60, name: "Fleur Hotels Pvt. Ltd.", location: "Udaipur" },
    { id: 61, name: "Schloss Udaipur Private Limited", location: "Udaipur" },
    { id: 62, name: "ESPIRE Resorts Private Ltd.", location: "Sawai Madopur" },
    { id: 63, name: "Miraj Hotels Pvt. Ltd.", location: "Nathdwara" },
    { id: 64, name: "The Indian Hotels Company Ltd.", location: "Jaipur" },
    { id: 65, name: "Gram Panchayat Piprali", location: "Sikar" },
    { id: 66, name: "B K Birla Institute & Engineering & Technology", location: "Pilani" },
    { id: 67, name: "B K Birla Institute of Higher Education", location: "Pilani" },
    { id: 68, name: "Aditya Vikram Birla Memorial", location: "Pilani" },
    { id: 69, name: "Asian Quaartrz Private Limited", location: "Banswara" },
    { id: 70, name: "Aman Exports International", location: "Sitapura" },
    { id: 71, name: "Rajasthan Rajya Tilhan Utpadak Sahkari Sangh Ltd.", location: "Kota" },
    { id: 72, name: "Sonalac Panits and Coatings Ltd.", location: "Banswara" },
    { id: 73, name: "Bhanwar Singh Palace", location: "Pushkar" },
    { id: 74, name: "HMT Machine Tools Ltd.", location: "Ajmer" },
    { id: 75, name: "BK BIRLA ENGINEERING", location: "JAIPUR" },
];

export default clients;